POST http://localhost:6363/data/indextest/_query
content-type: application/json

{
    "selector": {"opinions":"it is good"},
    "use_index": "idx-opinions-hobby",
    "fields":["hobby", "opinions"]
}
