name: End To End

on: [push, pull_request]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x
      - run: |
          deno upgrade --version 1.15.3
          touch .env
          echo awsAccessKeyId=${{ secrets.AWSACCESSKEYID }} >> .env
          echo awsSecretKey=${{ secrets.AWSSECRETKEY }} >> .env
          echo region=${{ secrets.REGION }} >> .env
          echo DynamoDbTable=${{ secrets.TABLENAME }} >> .env
          ./scripts/harness.sh && HYPER=http://localhost:6363/test deno test --allow-net --allow-env --import-map=https://x.nest.land/hyper-test@0.0.2/import_map.json https://x.nest.land/hyper-test@0.0.2/mod.js
          rm .env
